### SUCCEDS LOGIN
POST http://localhost:3003/api/v1.0/login 
Content-Type: application/json

{
  "username": "userNumber1",
  "password": "userNumber1"
}

### SUCCEDS LOGIN AOTHER USER
POST http://localhost:3003/api/v1.0/login 
Content-Type: application/json

{

  "username": "userNumber2",
  "password": "userNumber2"
}

### WRONG LOGIN
POST http://localhost:3003/api/v1.0/login 
Content-Type: application/json

{

  "username": "userNumber1",
  "password": "wrongPassword"
}

### WRONG LOGIN
POST http://localhost:3003/api/v1.0/login 
Content-Type: application/json

{

  "username": "userNumber1",
  "password": "wrong password with spaces"
}