// All of the movies
###
GET http://localhost:3003/api/v1.0/movies

// All of the movies with queries page and pageSize
###
GET http://localhost:3003/api/v1.0/movies?page=2&pageSize=5

###    // One movie
GET http://localhost:3003/api/v1.0/movies/9799 HTTP/1.1

###    // One movie detail
GET http://localhost:3003/api/v1.0/movies/9799/detail HTTP/1.1

###    // One movie tmdb
GET http://localhost:3003/api/v1.0/movies/9799/tmdb HTTP/1.1

###    // Popular movies
GET http://localhost:3003/api/v1.0/movies/popular?page=500 HTTP/1.1

###    // Latest movies
GET http://localhost:3003/api/v1.0/movies/latest?page=80 HTTP/1.1

###    // Trending movies
GET http://localhost:3003/api/v1.0/movies/trending?page=501 HTTP/1.1

###    // Search movies by query
GET http://localhost:3003/api/v1.0/movies/search?query=mario&page=14 HTTP/1.1

###    // Get movies by genre
GET http://localhost:3003/api/v1.0/movies/genre?genres=28&page=500

###   // All of the reviews of one movie
GET http://localhost:3003/api/v1.0/movies/9799/reviews HTTP/1.1

###   // All of the reviews of one movie with queries page and pageSize
GET http://localhost:3003/api/v1.0/movies/9799/reviews?page=1&pageSize=1 HTTP/1.1

###   // One review of one movie
GET http://localhost:3003/api/v1.0/movies/9799/reviews/64493b16236a412ea5eb6550 HTTP/1.1

###   // One review of one movie with WRONG id of review
GET http://localhost:3003/api/v1.0/movies/9799/reviews/64493b16236a412ea5eb6559 HTTP/1.1

###   // One movie review for specific user
GET http://localhost:3003/api/v1.0/movies/9799/reviewUser HTTP/1.1

###   // One movie rate for specific user
GET http://localhost:3003/api/v1.0/movies/9799/rateUser HTTP/1.1



###   // Add one review
POST http://localhost:3003/api/v1.0/movies/343622/reviews
Content-Type: application/json

{
  "title": "Title of review 1",
  "body": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenati"
}

###   // Edit review - Review made by userNumber0
PUT http://localhost:3003/api/v1.0/movies/9799/reviews/64493b16236a412ea5eb6550
Content-Type: application/json

{
  "title": "Title of review changed",
  "body": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenati Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenati"
}

###   // Delete review - By userNumber0
DELETE http://localhost:3003/api/v1.0/movies/9799/reviews/64493b16236a412ea5eb6550


###   // Add one rate
POST http://localhost:3003/api/v1.0/movies/253835/rates
Content-Type: application/json

{
  "value": "1"
}

###   // Edit rate
PUT http://localhost:3003/api/v1.0/movies/9799/rates/64502ae06dc338b6e80b8c59
Content-Type: application/json

{
  "value": "10"
}

###   // Delete rate - By userNumber1
DELETE http://localhost:3003/api/v1.0/movies/9799/rates/64502ae06dc338b6e80b8c5a