### // CREATE NEW USER
POST http://localhost:3003/api/v1.0/users HTTP/1.1
Content-Type: application/json

{
      "username": "mluukkai",
      "password": "password1"
}

### // CREATE ANOTHER USER
POST http://localhost:3003/api/v1.0/users HTTP/1.1
Content-Type: application/json

{
      "username": "Peters",
      "password": "password2"
}

### // ATTEMPTING TO CREATE A USER WITH TAKEN USERNAME. TRY THIS AFTER THE PREVIOUS.
POST http://localhost:3003/api/v1.0/users HTTP/1.1
Content-Type: application/json

{
      "username": "Peters",
      "password": "password2"
}

### // ATTEMPTING TO CREATE A USER WITH USERNAME TOO SHORT
POST http://localhost:3003/api/v1.0/users HTTP/1.1
Content-Type: application/json

{
      "username": "Pet",
      "password": "password2"
}

###    // GET USER USERNUMBER0
GET http://localhost:3003/api/v1.0/users/64501354c41b5db06e01c5a4 HTTP/1.1

###    // GET USER USERNUMBER10
GET http://localhost:3003/api/v1.0/users/64501354c41b5db06e01c5ae HTTP/1.1

###    // GET USER USERNUMBER11 -  USER WITHOUT REVIEWS
GET http://localhost:3003/api/v1.0/users/64501354c41b5db06e01c5af HTTP/1.1

###    // GET USER USERNUMBER1
GET http://localhost:3003/api/v1.0/users/64501354c41b5db06e01c5a5 HTTP/1.1


### // DELETE USERNUMBER1
DELETE http://localhost:3003/api/v1.0/users/64501354c41b5db06e01c5a5 HTTP/1.1


# EDIT USERS WITH USERNUMBER0
###    // EDIT USER VALID FILE
PUT http://localhost:3003/api/v1.0/users/64501354c41b5db06e01c5a4 HTTP/1.1
Content-Type: multipart/form-data; boundary=----boundary

------boundary
Content-Disposition: form-data; name="username"

userNumber0Change1
------boundary
Content-Disposition: form-data; name="password"

passwordChanged
------boundary
Content-Disposition: form-data; name="bio"

Bio of the user 0     remove unnecessary spaces
------boundary
Content-Disposition: form-data; name="photo"; filename="2.jpg"
Content-Type: image/jpg

< ./2.jpg
------boundary--


###    // EDIT USER VALID WWITHOUT FILE
PUT http://localhost:3003/api/v1.0/users/64501354c41b5db06e01c5a4 HTTP/1.1
Content-Type: multipart/form-data; boundary=----boundary

------boundary
Content-Disposition: form-data; name="username"

userNumber0Change2
------boundary
Content-Disposition: form-data; name="password"

passwordChanged2
------boundary
Content-Disposition: form-data; name="bio"

Bio of the user 0     remove unnecessary spaces
------boundary--


###    // EDIT USER WRONG - MISSING FIELD BIO
PUT http://localhost:3003/api/v1.0/users/64501354c41b5db06e01c5a4 HTTP/1.1
Content-Type: multipart/form-data; boundary=----boundary

------boundary
Content-Disposition: form-data; name="username"

userNumber0Change3
------boundary
Content-Disposition: form-data; name="password"

passwordChanged
------boundary
Content-Disposition: form-data; name="photo"; filename="1.jpg"
Content-Type: image/jpg

< ./1.jpg
------boundary--


###    // EDIT USER WRONG - DON'T PASS VALIDATION
PUT http://localhost:3003/api/v1.0/users/64501354c41b5db06e01c5a4 HTTP/1.1
Content-Type: multipart/form-data; boundary=----boundary

------boundary
Content-Disposition: form-data; name="username"

u
------boundary
Content-Disposition: form-data; name="password"

p
------boundary
Content-Disposition: form-data; name="bio"

Bio of the user 0     remove unnecessary spaces
------boundary
Content-Disposition: form-data; name="photo"; filename="1.jpg"
Content-Type: image/jpg

< ./1.jpg
------boundary--

###    // EDIT USER WRONG - USERNAME TAKEN
PUT http://localhost:3003/api/v1.0/users/64501354c41b5db06e01c5a4 HTTP/1.1
Content-Type: multipart/form-data; boundary=----boundary

------boundary
Content-Disposition: form-data; name="username"

userNumber1
------boundary
Content-Disposition: form-data; name="password"

passwordChanged
------boundary
Content-Disposition: form-data; name="bio"

Bio of the user 0     remove unnecessary spaces
------boundary
Content-Disposition: form-data; name="photo"; filename="1.jpg"
Content-Type: image/jpg

< ./1.jpg
------boundary--


###    // EDIT USER WRONG - FILE TOO BIG > 1MB
PUT http://localhost:3003/api/v1.0/users/64501354c41b5db06e01c5a4 HTTP/1.1
Content-Type: multipart/form-data; boundary=----boundary

------boundary
Content-Disposition: form-data; name="username"

userNumber0Change3
------boundary
Content-Disposition: form-data; name="password"

passwordChanged
------boundary
Content-Disposition: form-data; name="bio"

Bio of the user 0     remove unnecessary spaces
------boundary
Content-Disposition: form-data; name="photo"; filename="3.jpg"
Content-Type: image/jpg

< ./3.jpg
------boundary--


###    // EDIT USER WRONG FILE EXTENSION
PUT http://localhost:3003/api/v1.0/users/64501354c41b5db06e01c5a4 HTTP/1.1
Content-Type: multipart/form-data; boundary=----boundary

------boundary
Content-Disposition: form-data; name="username"

userNumber0Change4
------boundary
Content-Disposition: form-data; name="password"

passwordChanged
------boundary
Content-Disposition: form-data; name="bio"

Bio of the user 0     remove unnecessary spaces
------boundary
Content-Disposition: form-data; name="photo"; filename="4.svg"
Content-Type: image/jpg

< ./4.svg
------boundary--


###    // EDIT USER WRONG FILE TYPE - PDF WITH EXTENSION OF VALID TYPE
PUT http://localhost:3003/api/v1.0/users/64501354c41b5db06e01c5a4 HTTP/1.1
Content-Type: multipart/form-data; boundary=----boundary

------boundary
Content-Disposition: form-data; name="username"

userNumber0Change5
------boundary
Content-Disposition: form-data; name="password"

passwordChanged
------boundary
Content-Disposition: form-data; name="bio"

Bio of the user 0     remove unnecessary spaces
------boundary
Content-Disposition: form-data; name="photo"; filename="5.png"
Content-Type: image/jpg

< ./5.png
------boundary--


###    // EDIT USER INVALID FILE
PUT http://localhost:3003/api/v1.0/users/64501354c41b5db06e01c5a4 HTTP/1.1
Content-Type: multipart/form-data; boundary=----boundary

------boundary
Content-Disposition: form-data; name="username"

userNumber0Change6
------boundary
Content-Disposition: form-data; name="password"

passwordChanged
------boundary
Content-Disposition: form-data; name="bio"

Bio of the user 0     remove unnecessary spaces
------boundary
Content-Disposition: form-data; name="photo"; filename="1.jpg"
Content-Type: image/jpg

< ./.jpg
------boundary--


###    // GET USER/REVIEWS USERNUMBER0 - USER WITH REVIEWS
GET http://localhost:3003/api/v1.0/users/64501354c41b5db06e01c5a4/reviews?page=1&pageSize=1  HTTP/1.1

### // GET USER/REVIEWS USERNUMBER11 -  USER WITHOUT REVIEWS
GET http://localhost:3003/api/v1.0/users/64501354c41b5db06e01c5af/reviews?page=0&pageSize=1 HTTP/1.1


### // GET USER/RATES USERNUMBER1 -  USER WITH RATES
GET  http://localhost:3003/api/v1.0/users/64501354c41b5db06e01c5a5/rates?page=0&pageSize=1 HTTP/1.1

###    // GET USER/RATES USERNUMBER10 - USER WITHOUT RATES
GET http://localhost:3003/api/v1.0/users/64501354c41b5db06e01c5ae/rates HTTP/1.1

###    // GET USER/LISTS USERNUMBER0 - USER WITH LISTS
GET http://localhost:3003/api/v1.0/users/64501354c41b5db06e01c5a4/lists  HTTP/1.1

###    // GET USER/LISTS USERNUMBER0 - USER WITH LISTS
GET http://localhost:3003/api/v1.0/users/64501354c41b5db06e01c5a4/lists?page=0&pageSize=1  HTTP/1.1

### // GET USER/LISTS USERNUMBER11 -  USER WITHOUT LISTS
GET http://localhost:3003/api/v1.0/users/64501354c41b5db06e01c5af/lists?page=0&pageSize=1 HTTP/1.1

###    // GET USER/LISTS/:LISTID USERNUMBER0 - USER WITH LISTS
GET http://localhost:3003/api/v1.0/users/64501354c41b5db06e01c5a4/lists/64502ae06dc338b6e80b8c58  HTTP/1.1

###    // GET USER/LISTS/:LISTID USERNUMBER0 - USER WITH LISTS
GET http://localhost:3003/api/v1.0/users/64501354c41b5db06e01c5a4/lists/64502ae06dc338b6e80b8c55  HTTP/1.1

###    // GET USER/LISTS/:LISTID USERNUMBER0 - USER WITH LISTS
GET http://localhost:3003/api/v1.0/users/64501354c41b5db06e01c5a4/lists/64502ae06dc338b6e80b8c55?page=1&pageSize=1&light=0  HTTP/1.1

###    // GET USER/LISTS/:LISTID USERNUMBER0 - USER WITH LISTS
GET http://localhost:3003/api/v1.0/users/64501354c41b5db06e01c5a4/lists/64502ae06dc338b6e80b8c55?light=1  HTTP/1.1


###    // CREATE LIST USERNUMBER0 - USER WITH LISTS
POST http://localhost:3003/api/v1.0/users/64501354c41b5db06e01c5a4/lists  HTTP/1.1
Content-Type: application/json

{
      "name": "New list created by userNumber0"
}

###    // EDIT LIST USERNUMBER0 - USER WITH LISTS
PUT http://localhost:3003/api/v1.0/users/64501354c41b5db06e01c5a4/lists/64502ae06dc338b6e80b8c58  HTTP/1.1
Content-Type: application/json

{
      "name": "List number 3 edited",
      "description": "new description to this list",
      "movies": ["82992"]
}


###    // EDIT LIST USERNUMBER0 - USER WITH LISTS
PUT http://localhost:3003/api/v1.0/users/64501354c41b5db06e01c5a4/lists/64502ae06dc338b6e80b8c58  HTTP/1.1
Content-Type: application/json

{
      "name": "List number 3 edited",
      "description": "new description to this list",
      "movies": ["13804", "82992", "584", "77959", "675353", "675353"]
}

###    // EDIT LIST USERNUMBER0 - USER WITH LISTS - EMPTY ARRAY
PUT http://localhost:3003/api/v1.0/users/64501354c41b5db06e01c5a4/lists/64502ae06dc338b6e80b8c58  HTTP/1.1
Content-Type: application/json

{
      "name": "List number 3 edited",
      "description": "new description to this list",
      "movies": []
}

###    // EDIT LIST USERNUMBER0 - USER WITH LISTS - WRONG MOVIES FIELD
PUT http://localhost:3003/api/v1.0/users/64501354c41b5db06e01c5a4/lists/64502ae06dc338b6e80b8c58  HTTP/1.1
Content-Type: application/json

{
      "name": "List number 3 edited",
      "description": "new description to this list",
      "movies": "String"
}